services:
  backend:
    build: .
    container_name: heart-disease-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./src/heart_disease/frontend
    container_name: heart-disease-frontend
    ports:
      - "5173:5173"
    restart: unless-stopped