[project]
name = "heart-disease"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shiv", email = "117908887+Dreamy-Keys@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "pytest>=9.1.1",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "uvicorn>=0.54.0",
]

[project.scripts]
heart-disease = "heart_disease.backend.app.main:start"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"


[tool.fastapi]
entrypoint = "heart_disease.backend.app.main:app"
