import type { PredictionResult as PredictionResultType } from "../services/api"

type PredictionResultProps = {
  result: PredictionResultType
}

function PredictionResult({ result }: PredictionResultProps) {
  return (
    <div
      className={`result-card ${
        result.prediction === 1
          ? "result-positive"
          : "result-negative"
      }`}
    >
      <h2>Prediction Result</h2>

      <p className="result-text">
        {result.result}
      </p>

      <div className="probability">
        <span>Model probability</span>

        <strong>
          {(result.probability * 100).toFixed(1)}%
        </strong>
      </div>

      <div className="probability-bar">
        <div
          className="probability-fill"
          style={{
            width: `${result.probability * 100}%`,
          }}
        />
      </div>

      <p className="disclaimer">
        This prediction is generated by a machine learning
        model for demonstration purposes only and is not a
        medical diagnosis.
      </p>
    </div>
  )
}

export default PredictionResult